# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 08:26
from __future__ import unicode_literals

from __future__ import absolute_import
import autoslug.fields
import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# activities.migrations.0006_copy_instructors
# activities.migrations.0010_copy_extra
# activities.migrations.0022_instructors_uuid

class Migration(migrations.Migration):

    replaces = [('activities', '0001_initial'), ('activities', '0002_course_responsible'), ('activities', '0003_auto_20160708_1540'), ('activities', '0004_course_visible'), ('activities', '0005_course_instructors'), ('activities', '0006_copy_instructors'), ('activities', '0007_remove_course_responsible'), ('activities', '0008_extraneed_types'), ('activities', '0009_link_to_courses'), ('activities', '0010_copy_extra'), ('activities', '0011_remove_extraneed_activity'), ('activities', '0012_default_extraneed_value'), ('activities', '0013_course_name'), ('activities', '0014_auto_20170112_1205'), ('activities', '0015_auto_20170728_1716'), ('activities', '0016_course_announced_js'), ('activities', '0017_course_price_description'), ('activities', '0018_extraneed_price_reduction'), ('activities', '0019_auto_20190830_2118'), ('activities', '0020_auto_20190830_2125'), ('activities', '0021_course_comments'), ('activities', '0022_instructors_uuid'), ('activities', '0023_remove_course_instructors')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0014_switch_pk_to_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name')),
                ('number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Identifier')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Part of the url. Cannot contain punctuation, spaces or accentuated letters', populate_from='name', unique=True)),
                ('informations', ckeditor.fields.RichTextField(blank=True, help_text='Specific informations like outfit.', verbose_name='Informations')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Identifier')),
                ('uptodate', models.BooleanField(default=True, verbose_name='Course up to date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('number_of_sessions', models.PositiveSmallIntegerField(verbose_name='Number of sessions')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, verbose_name='Day')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('place', models.TextField(verbose_name='Place')),
                ('min_participants', models.PositiveSmallIntegerField(verbose_name='Minimal number of participants')),
                ('max_participants', models.PositiveSmallIntegerField(verbose_name='Maximal number of participants')),
                ('schoolyear_min', models.PositiveIntegerField(choices=[(1, '1st HARMOS'), (2, '2nd HARMOS'), (3, '3rd HARMOS'), (4, '4th HARMOS'), (5, '5th HARMOS'), (6, '6th HARMOS'), (7, '7th HARMOS'), (8, '8th HARMOS'), (9, '9th HARMOS'), (10, '10th HARMOS'), (11, '11th HARMOS'), (12, '12th HARMOS')], default='1', verbose_name='Minimal school year')),
                ('schoolyear_max', models.PositiveIntegerField(choices=[(1, '1st HARMOS'), (2, '2nd HARMOS'), (3, '3rd HARMOS'), (4, '4th HARMOS'), (5, '5th HARMOS'), (6, '6th HARMOS'), (7, '7th HARMOS'), (8, '8th HARMOS'), (9, '9th HARMOS'), (10, '10th HARMOS'), (11, '11th HARMOS'), (12, '12th HARMOS')], default='12', verbose_name='Maximal school year')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='activities.Activity', verbose_name='Activity')),
                ('visible', models.BooleanField(default=True, verbose_name='Course visible')),
            ],
            options={
                'ordering': ('activity__name', 'number'),
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='ExtraNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('question_label', models.CharField(help_text='e.g. Shoes size?', max_length=255, verbose_name='Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='extraneed',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), null=True, size=None),
        ),
        migrations.AddField(
            model_name='extraneed',
            name='default',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extraneed',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extraneed',
            name='type',
            field=models.CharField(choices=[('B', 'Boolean'), ('C', 'Characters'), ('I', 'Integer')], default='C', max_length=2, verbose_name='Type of answer'),
        ),
        migrations.AlterModelOptions(
            name='extraneed',
            options={'verbose_name': 'extra question', 'verbose_name_plural': 'extra questions'},
        ),
        migrations.AddField(
            model_name='extraneed',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='extra', to='activities.Course'),
        ),
        migrations.AddField(
            model_name='extraneed',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extraneed',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Limit to values (internal name, display name),(internal name 2, display name 2)'),
        ),
        migrations.AlterField(
            model_name='extraneed',
            name='default',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default value'),
        ),

        migrations.AlterField(
            model_name='course',
            name='schoolyear_max',
            field=models.PositiveIntegerField(choices=[(1, '1P'), (2, '2P'), (3, '3P'), (4, '4P'), (5, '5P'), (6, '6P'), (7, '7P'), (8, '8P'), (9, '9S'), (10, '10S'), (11, '11S'), (12, '12S')], default='12', verbose_name='Maximal school year'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schoolyear_min',
            field=models.PositiveIntegerField(choices=[(1, '1P'), (2, '2P'), (3, '3P'), (4, '4P'), (5, '5P'), (6, '6P'), (7, '7P'), (8, '8P'), (9, '9S'), (10, '10S'), (11, '11S'), (12, '12S')], default='1', verbose_name='Minimal school year'),
        ),
        migrations.AlterField(
            model_name='extraneed',
            name='default',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Default value'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Displayed name'),
        ),
        migrations.AlterField(
            model_name='extraneed',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='extra', to='activities.Course'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='informations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Specific informations like outfit.', verbose_name='Informations'),
        ),
        migrations.AddField(
            model_name='course',
            name='announced_js',
            field=models.BooleanField(default=False, verbose_name='Course announced to J+S'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_description',
            field=models.TextField(blank=True, verbose_name='Informations about pricing'),
        ),
        migrations.AddField(
            model_name='extraneed',
            name='price_reduction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None, verbose_name='reduce price by xx francs if this value is selected'),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_sessions',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of sessions'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start date'),
        ),
        migrations.AddField(
            model_name='course',
            name='comments',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Comments'),
        ),
        migrations.CreateModel(
            name='CoursesInstructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coursesinstructors',
            unique_together=set([('course', 'instructor')]),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='course', through='activities.CoursesInstructors', to=settings.AUTH_USER_MODEL, verbose_name='Instructors'),
        ),
    ]
