# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 16:09
from __future__ import unicode_literals

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name')),
                ('number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Identifier')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Part of the url. Cannot contain punctuation, spaces or accentuated letters', populate_from=b'name', unique=True)),
                ('informations', ckeditor.fields.RichTextField(blank=True, help_text='Specific informations like outfit.', verbose_name='Informations')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'activit\xe9',
                'verbose_name_plural': 'activit\xe9s',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Identifier')),
                ('uptodate', models.BooleanField(default=True, verbose_name='Course up to date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('number_of_sessions', models.PositiveSmallIntegerField(verbose_name='Number of sessions')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, verbose_name='Day')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('place', models.TextField(verbose_name='Place')),
                ('min_participants', models.PositiveSmallIntegerField(verbose_name='Minimal number of participants')),
                ('max_participants', models.PositiveSmallIntegerField(verbose_name='Maximal number of participants')),
                ('schoolyear_min', models.PositiveIntegerField(choices=[(1, '1st HARMOS'), (2, '2nd HARMOS'), (3, '3rd HARMOS'), (4, '4th HARMOS'), (5, '5th HARMOS'), (6, '6th HARMOS'), (7, '7th HARMOS'), (8, '8th HARMOS'), (9, '9th HARMOS'), (10, '10th HARMOS'), (11, '11th HARMOS'), (12, '12th HARMOS')], default=b'1', verbose_name='Minimal school year')),
                ('schoolyear_max', models.PositiveIntegerField(choices=[(1, '1st HARMOS'), (2, '2nd HARMOS'), (3, '3rd HARMOS'), (4, '4th HARMOS'), (5, '5th HARMOS'), (6, '6th HARMOS'), (7, '7th HARMOS'), (8, '8th HARMOS'), (9, '9th HARMOS'), (10, '10th HARMOS'), (11, '11th HARMOS'), (12, '12th HARMOS')], default=b'8', verbose_name='Maximal school year')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='activities.Activity', verbose_name='Activity')),
            ],
            options={
                'ordering': ('activity__name', 'number'),
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
            },
        ),
        migrations.CreateModel(
            name='ExtraNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('question_label', models.CharField(help_text='e.g. Shoes size?', max_length=255, verbose_name='Question')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='activities.Activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
