# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 05:21
import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_squashed_0023_remove_course_instructors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extraneed",
            old_name="price_reduction",
            new_name="price_modifier",
        ),
        migrations.AlterField(
            model_name="extraneed",
            name="price_modifier",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                null=True,
                size=None,
                help_text="List of positive/negative values",
                verbose_name="Modify price by xx francs if this value is selected",
            ),
        ),
    ]
