# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 10:43
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0002_rename_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaySlip",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Rate")),
                (
                    "rate_mode",
                    models.CharField(
                        choices=[("day", "Daily"), ("hour", "Hourly")],
                        default="hour",
                        max_length=10,
                        verbose_name="Rate mode",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                ("function", models.CharField(max_length=255, verbose_name="Function")),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="payslip",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="activities.Course",
                verbose_name="Course",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instructor",
            ),
        ),
    ]
