# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 04:14
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_pay_slip"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="allocation_account",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Allocation account"
            ),
        )
    ]
