# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 04:41
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_auto_20210414_0614"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "account",
                    models.CharField(
                        help_text="e.g. 154.4652.00",
                        max_length=50,
                        unique=True,
                        verbose_name="Account",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Some text to help humans filter account numbers",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "ordering": ["account"],
                "verbose_name": "Allocation account",
                "verbose_name_plural": "Allocation accounts",
            },
        ),
        migrations.RemoveField(
            model_name="activity",
            name="allocation_account",
        ),
        migrations.AddField(
            model_name="activity",
            name="allocation_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="activities.AllocationAccount",
                verbose_name="Allocation account",
            ),
        ),
    ]
