# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 14:07
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0004_course_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                related_name="course", to=settings.AUTH_USER_MODEL, verbose_name="Instructors"
            ),
        ),
    ]
