# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 14:08
from __future__ import absolute_import, unicode_literals

from django.db import migrations


def make_many_instructors(apps, schema_editor):
    "Copy the responsible foreign key to the new instructors manytomany field"
    Course = apps.get_model("activities", "Course")
    for course in Course.objects.all():
        course.instructors.add(course.responsible)


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_course_instructors"),
        ("profiles", "0003_school"),
    ]

    operations = [migrations.RunPython(make_many_instructors)]
