# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 14:30
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20210414_0641'),
    ]

    operations = [

        migrations.AlterField(
            model_name='activity',
            name='allocation_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.AllocationAccount', verbose_name='Allocation account'),
        ),
        migrations.AlterField(
            model_name='allocationaccount',
            name='name',
            field=models.CharField(blank=True, help_text='Some text to help humans filter account numbers', max_length=50, verbose_name='Name'),
        ),

    ]
