# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-04 14:09
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20210414_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[(b'course', 'Course (single day per week)'), (b'multicourse', 'Course (multiple days per week)'), (b'camp', 'Camp')], default=b'course', max_length=16, verbose_name='Course type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='allocation_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.AllocationAccount', verbose_name='Allocation account'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Start time'),
        ),
    ]
