# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-07 14:44
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_add_camps"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="end_time_fri",
            field=models.TimeField(null=True, verbose_name="End time, fridays"),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time_mon",
            field=models.TimeField(null=True, verbose_name="End time, mondays"),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time_sat",
            field=models.TimeField(null=True, verbose_name="End time, saturdays"),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time_sun",
            field=models.TimeField(null=True, verbose_name="End time, sundays"),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time_thu",
            field=models.TimeField(null=True, verbose_name="End time, thursdays"),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time_tue",
            field=models.TimeField(null=True, verbose_name="End time, tuesdays"),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time_wed",
            field=models.TimeField(null=True, verbose_name="End time, wednesdays"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time_fri",
            field=models.TimeField(null=True, verbose_name="Start time, fridays"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time_mon",
            field=models.TimeField(null=True, verbose_name="Start time, mondays"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time_sat",
            field=models.TimeField(null=True, verbose_name="Start time, saturdays"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time_sun",
            field=models.TimeField(null=True, verbose_name="Start time, sundays"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time_thu",
            field=models.TimeField(null=True, verbose_name="Start time, thursdays"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time_tue",
            field=models.TimeField(null=True, verbose_name="Start time, tuesdays"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time_wed",
            field=models.TimeField(null=True, verbose_name="Start time, wednesdays"),
        ),
    ]
