# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-07 11:27
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_remove_course_responsible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["name"],
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("activity__name", "number"),
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.AddField(
            model_name="extraneed",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="extraneed",
            name="default",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="extraneed",
            name="mandatory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="extraneed",
            name="type",
            field=models.CharField(
                choices=[(b"B", "Boolean"), (b"C", "Characters"), (b"I", "Integer")],
                default=b"C",
                max_length=2,
                verbose_name="Type of answer",
            ),
        ),
    ]
