# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 07:29
from __future__ import unicode_literals

from __future__ import absolute_import
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_extraneed_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraneed',
            options={'verbose_name': 'extra question', 'verbose_name_plural': 'extra questions'},
        ),
        migrations.AddField(
            model_name='extraneed',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='extra', to='activities.Course'),
        ),
        migrations.AddField(
            model_name='extraneed',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extraneed',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Limit to values (internal name, display name),(internal name 2, display name 2)'),
        ),
        migrations.AlterField(
            model_name='extraneed',
            name='default',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default value'),
        ),
    ]
