# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-01 09:06
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0008_course_start_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price_family",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applied for the second and following members registered to the same course",
                max_digits=5,
                null=True,
                verbose_name="Price for family members",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price_local",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Price for local people",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price_local_family",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applied for the second and following members registered to the same course if the family is local",
                max_digits=5,
                null=True,
                verbose_name="Price for local family members",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="End time"),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_time_fri",
            field=models.TimeField(blank=True, null=True, verbose_name="End time, fridays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_time_mon",
            field=models.TimeField(blank=True, null=True, verbose_name="End time, mondays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_time_sat",
            field=models.TimeField(blank=True, null=True, verbose_name="End time, saturdays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_time_sun",
            field=models.TimeField(blank=True, null=True, verbose_name="End time, sundays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_time_thu",
            field=models.TimeField(blank=True, null=True, verbose_name="End time, thursdays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_time_tue",
            field=models.TimeField(blank=True, null=True, verbose_name="End time, tuesdays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_time_wed",
            field=models.TimeField(blank=True, null=True, verbose_name="End time, wednesdays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time_fri",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time, fridays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time_mon",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time, mondays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time_sat",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time, saturdays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time_sun",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time, sundays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time_thu",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time, thursdays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time_tue",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time, tuesdays"),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time_wed",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time, wednesdays"),
        ),
    ]
