# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 07:30
from django.db import migrations


def copy_activities_to_courses(apps, schema_editor):
    "Copy the responsible foreign key to the new instructors manytomany field"
    ExtraNeed = apps.get_model("activities", "ExtraNeed")
    for extra in ExtraNeed.objects.all():
        for course in extra.activity.courses.all():
            extra.courses.add(course)
        extra.save()


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0009_link_to_courses"),
    ]

    operations = [migrations.RunPython(copy_activities_to_courses)]
