# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-04 16:12
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatedEmailReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('convocation', 'Convocation to the course'), ('need_confirmation', 'Need parent confirmation'), ('not_paid', 'Payment reminder'), ('instructors', 'Documents for course instructor')], max_length=30, verbose_name='Email type')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='templatedemailreceipt',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Course'),
        ),
    ]
