# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_copy_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraneed',
            name='activity',
        ),
    ]
