# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-09 09:29
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0010_mail_receipts"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="age_max",
            field=models.PositiveIntegerField(
                choices=[
                    (5, "5 years old"),
                    (6, "6 years old"),
                    (7, "7 years old"),
                    (8, "8 years old"),
                    (9, "9 years old"),
                    (10, "10 years old"),
                    (11, "11 years old"),
                    (12, "12 years old"),
                    (13, "13 years old"),
                    (14, "14 years old"),
                    (15, "15 years old"),
                    (16, "16 years old"),
                    (17, "17 years old"),
                    (18, "18 years old"),
                ],
                help_text="At the beginning of course",
                null=True,
                blank=True,
                verbose_name="Minimal age",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="age_min",
            field=models.PositiveIntegerField(
                choices=[
                    (5, "5 years old"),
                    (6, "6 years old"),
                    (7, "7 years old"),
                    (8, "8 years old"),
                    (9, "9 years old"),
                    (10, "10 years old"),
                    (11, "11 years old"),
                    (12, "12 years old"),
                    (13, "13 years old"),
                    (14, "14 years old"),
                    (15, "15 years old"),
                    (16, "16 years old"),
                    (17, "17 years old"),
                    (18, "18 years old"),
                ],
                help_text="At the beginning of course",
                null=True,
                blank=True,
                verbose_name="Minimal age",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="schoolyear_max",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1P"),
                    (2, "2P"),
                    (3, "3P"),
                    (4, "4P"),
                    (5, "5P"),
                    (6, "6P"),
                    (7, "7P"),
                    (8, "8P"),
                    (9, "9S"),
                    (10, "10S"),
                    (11, "11S"),
                    (12, "12S"),
                ],
                null=True,
                blank=True,
                verbose_name="Maximal school year",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="schoolyear_min",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1P"),
                    (2, "2P"),
                    (3, "3P"),
                    (4, "4P"),
                    (5, "5P"),
                    (6, "6P"),
                    (7, "7P"),
                    (8, "8P"),
                    (9, "9S"),
                    (10, "10S"),
                    (11, "11S"),
                    (12, "12S"),
                ],
                null=True,
                blank=True,
                verbose_name="Minimal school year",
            ),
        ),
    ]
