# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 05:19
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_remove_extraneed_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schoolyear_max',
            field=models.PositiveIntegerField(choices=[(1, '1P'), (2, '2P'), (3, '3P'), (4, '4P'), (5, '5P'), (6, '6P'), (7, '7P'), (8, '8P'), (9, '9S'), (10, '10S'), (11, '11S'), (12, '12S')], default=b'12', verbose_name='Maximal school year'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schoolyear_min',
            field=models.PositiveIntegerField(choices=[(1, '1P'), (2, '2P'), (3, '3P'), (4, '4P'), (5, '5P'), (6, '6P'), (7, '7P'), (8, '8P'), (9, '9S'), (10, '10S'), (11, '11S'), (12, '12S')], default=b'1', verbose_name='Minimal school year'),
        ),
        migrations.AlterField(
            model_name='extraneed',
            name='default',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='Default value'),
        ),
    ]
