# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-09 15:16
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0011_add_ages"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="min_birth_date",
            field=models.DateField(
                editable=False, null=True, verbose_name="Minimal birth date to register"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="age_max",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (5, "5 years old"),
                    (6, "6 years old"),
                    (7, "7 years old"),
                    (8, "8 years old"),
                    (9, "9 years old"),
                    (10, "10 years old"),
                    (11, "11 years old"),
                    (12, "12 years old"),
                    (13, "13 years old"),
                    (14, "14 years old"),
                    (15, "15 years old"),
                    (16, "16 years old"),
                    (17, "17 years old"),
                    (18, "18 years old"),
                ],
                help_text="At the beginning of course",
                null=True,
                verbose_name="Maximal age",
            ),
        ),
        migrations.AlterField(
            model_name="templatedemailreceipt",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_receipts",
                to="activities.Course",
            ),
        ),
    ]
