# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-09 16:31
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0012_auto_20210809_1716"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="max_birth_date",
            field=models.DateField(
                editable=False, null=True, verbose_name="Maximal birth date to register"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="age_max",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (5, "5 ans"),
                    (6, "6 ans"),
                    (7, "7 ans"),
                    (8, "8 ans"),
                    (9, "9 ans"),
                    (10, "10 ans"),
                    (11, "11 ans"),
                    (12, "12 ans"),
                    (13, "13 ans"),
                    (14, "14 ans"),
                    (15, "15 ans"),
                    (16, "16 ans"),
                    (17, "17 ans"),
                    (18, "18 ans"),
                ],
                help_text="At the beginning of course",
                null=True,
                verbose_name="Maximal age",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="age_min",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (5, "5 ans"),
                    (6, "6 ans"),
                    (7, "7 ans"),
                    (8, "8 ans"),
                    (9, "9 ans"),
                    (10, "10 ans"),
                    (11, "11 ans"),
                    (12, "12 ans"),
                    (13, "13 ans"),
                    (14, "14 ans"),
                    (15, "15 ans"),
                    (16, "16 ans"),
                    (17, "17 ans"),
                    (18, "18 ans"),
                ],
                help_text="At the beginning of course",
                null=True,
                verbose_name="Minimal age",
            ),
        ),
    ]
