# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 08:20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0012_default_extraneed_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Displayed name"
            ),
        ),
    ]
