# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:41
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20150723_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='Part of the url. Cannot contain punctuation, spaces or accentuated letters', populate_from=b'name', unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='schoolyear_max',
            field=models.PositiveIntegerField(choices=[(1, '1st HARMOS'), (2, '2nd HARMOS'), (3, '3rd HARMOS'), (4, '4th HARMOS'), (5, '5th HARMOS'), (6, '6th HARMOS'), (7, '7th HARMOS'), (8, '8th HARMOS'), (9, '9th HARMOS'), (10, '10th HARMOS'), (11, '11th HARMOS'), (12, '12th HARMOS')], default=b'8', verbose_name='Maximal school year'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schoolyear_min',
            field=models.PositiveIntegerField(choices=[(1, '1st HARMOS'), (2, '2nd HARMOS'), (3, '3rd HARMOS'), (4, '4th HARMOS'), (5, '5th HARMOS'), (6, '6th HARMOS'), (7, '7th HARMOS'), (8, '8th HARMOS'), (9, '9th HARMOS'), (10, '10th HARMOS'), (11, '11th HARMOS'), (12, '12th HARMOS')], default=b'1', verbose_name='Minimal school year'),
        ),
    ]
