# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-30 08:46
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20210809_1831'),
    ]

    operations = [

        migrations.AddField(
            model_name='course',
            name='nb_participants',
            field=models.SmallIntegerField(default=0, verbose_name='Current nb of participants'),
        ),
    ]
