# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 11:05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0013_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraneed",
            name="courses",
            field=models.ManyToManyField(blank=True, related_name="extra", to="activities.Course"),
        ),
    ]
