# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-25 08:45
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20210730_1033'),
        ('activities', '0014_auto_20210830_1046'),
    ]

    operations = [

        migrations.AddField(
            model_name='course',
            name='local_city_override',
            field=models.ManyToManyField(to='profiles.City', verbose_name='Local city override'),
        ),
    ]
