# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-28 15:16
from __future__ import absolute_import, unicode_literals

from django.db import migrations

import ckeditor_uploader.fields


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0014_auto_20170112_1205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="informations",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="Specific informations like outfit.",
                verbose_name="Informations",
            ),
        ),
    ]
