# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-20 16:14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0015_auto_20170728_1716"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="announced_js",
            field=models.BooleanField(default=False, verbose_name="Course announced to J+S"),
        ),
    ]
