# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 06:49
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
        ("activities", "0015_add_local_city_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesinstructors",
            name="function",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="payroll.Function"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="age_max",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (4, "4 ans"),
                    (5, "5 ans"),
                    (6, "6 ans"),
                    (7, "7 ans"),
                    (8, "8 ans"),
                    (9, "9 ans"),
                    (10, "10 ans"),
                    (11, "11 ans"),
                    (12, "12 ans"),
                    (13, "13 ans"),
                    (14, "14 ans"),
                    (15, "15 ans"),
                    (16, "16 ans"),
                    (17, "17 ans"),
                    (18, "18 ans"),
                ],
                help_text="At the beginning of course",
                null=True,
                verbose_name="Maximal age",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="age_min",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (4, "4 ans"),
                    (5, "5 ans"),
                    (6, "6 ans"),
                    (7, "7 ans"),
                    (8, "8 ans"),
                    (9, "9 ans"),
                    (10, "10 ans"),
                    (11, "11 ans"),
                    (12, "12 ans"),
                    (13, "13 ans"),
                    (14, "14 ans"),
                    (15, "15 ans"),
                    (16, "16 ans"),
                    (17, "17 ans"),
                    (18, "18 ans"),
                ],
                help_text="At the beginning of course",
                null=True,
                verbose_name="Minimal age",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="local_city_override",
            field=models.ManyToManyField(
                blank=True, null=True, to="profiles.City", verbose_name="Local city override"
            ),
        ),
    ]
