# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 03:36
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0016_course_announced_js"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price_description",
            field=models.TextField(blank=True, verbose_name="Informations about pricing"),
        ),
    ]
