# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 17:04
from __future__ import unicode_literals

from __future__ import absolute_import
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_course_price_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraneed',
            name='price_reduction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None, verbose_name='reduce price by xx francs if this value is selected'),
        ),
    ]
