# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-18 16:03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0018_auto_20220818_1759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[("activity", "Activities")],
                db_index=True,
                default="activity",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
