# Generated by Django 3.2.16 on 2022-12-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_auto_20220818_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='allocation_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.allocationaccount', verbose_name='Allocation account'),
        ),
    ]
