# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-30 19:25
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_auto_20190830_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_sessions',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of sessions'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start date'),
        ),
    ]
