# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 15:47
from django.db import migrations

import ckeditor_uploader.fields


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0020_auto_20190830_2125"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="comments",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Comments"
            ),
        ),
    ]
