# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 15:47
from __future__ import unicode_literals

from __future__ import absolute_import
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_auto_20190830_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comments',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Comments'),
        ),
    ]
