# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 15:20
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# noinspection PyPep8Naming
def fill_instructors_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Course = apps.get_model("activities", "Course")
    CoursesInstructors = apps.get_model("activities", "CoursesInstructors")

    for course in Course.objects.using(db_alias).prefetch_related("instructors"):
        for instructor in course.instructors.all():
            CoursesInstructors.objects.create(course=course, instructor=instructor.uuid)


# noinspection PyPep8Naming
def revert_fill_instructors_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Course = apps.get_model("activities", "Course")
    FamilyUser = apps.get_model("profiles", "FamilyUser")
    for course in Course.objects.using(db_alias).prefetch_related("coursesinstructors_set"):
        for course_instructor in course.courseinstructors_set.all():
            instructor = FamilyUser.objects.get(uuid=course_instructor.instructor)
            course.instructors.add(instructor)


class Migration(migrations.Migration):

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0021_course_comments"),
        ("profiles", "0013_add_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursesInstructors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="activities.Course"
                    ),
                ),
                ("instructor", models.UUIDField(null=False)),
            ],
        ),
        migrations.RunPython(fill_instructors_uuid, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="course",
            name="instructors",
        ),
    ]
