# Generated by Django 3.2.20 on 2023-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_auto_20230321_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraneed',
            name='display_image_field',
            field=models.BooleanField(default=False, verbose_name='Display image field'),
        ),
    ]
