# Generated by Django 3.2.20 on 2024-03-06 09:56

import django.contrib.postgres.fields
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_alter_extraneed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schoolyear_max',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1H'), (2, '2H'), (3, '3H'), (4, '4H'), (5, '5H'), (6, '6H'), (7, '7H'), (8, '8H'), (9, '9H'), (10, '10H'), (11, '11H'), (12, '12H')], null=True, verbose_name='Maximal school year'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schoolyear_min',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1H'), (2, '2H'), (3, '3H'), (4, '4H'), (5, '5H'), (6, '6H'), (7, '7H'), (8, '8H'), (9, '9H'), (10, '10H'), (11, '11H'), (12, '12H')], null=True, verbose_name='Minimal school year'),
        ),
        migrations.AlterField(
            model_name='extraneed',
            name='price_modifier',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='List of positive/negative values, if boolean: False value then True', null=True, size=None, verbose_name='Modify price by xx francs if this value is selected'),
        ),
        migrations.AddField(
            model_name='activity',
            name='managers',
            field=models.ManyToManyField(related_name='managed_activities', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Managers', blank=True),
        ),
    ]
