# Generated by Django 3.2.20 on 2024-09-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_add_restricted_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_new_participants',
            field=models.BooleanField(default=True,
                                      help_text='If unchecked, no new registration will be possible. This is more restrictive than the course being full.',
                                      verbose_name='Allow registrations'),

        ),
    ]
