# Generated by Django 3.2.20 on 2024-09-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_course_allow_new_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='places_available_reminder_sent_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Places available reminder sent on'),
        ),
    ]
