# Generated by Django 3.2.25 on 2024-10-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_wizardstep_link_display'),
        ('activities', '0025_course_places_available_reminder_sent_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraneed',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.wizardstep', verbose_name='Wizard step'),
        ),
    ]
