# Generated by Django 3.2.25 on 2024-10-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_wizardstep_link_display'),
        ('activities', '0026_extraneed_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraneed',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='wizard.wizardstep', verbose_name='Wizard step'),
        ),
    ]
