# Generated by Django 3.2.25 on 2024-10-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_alter_extraneed_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraneed',
            name='image_label',
            field=models.CharField(blank=True, help_text='if type is image', max_length=255, verbose_name='Image label'),
        ),
    ]
