# Generated by Django 3.2.25 on 2025-08-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_auto_20250804_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('course', 'Course (single day per week)'), ('unregistered_course', 'Unregistered course (single day per week)'), ('multicourse', 'Course (multiple days per week)'), ('camp', 'Camp')], default='course', max_length=30, verbose_name='Course type'),
        ),
    ]
