# Generated by Django 3.2.25 on 2025-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('course', 'Course (single day per week)'), ('unregistered_course', 'Unregistered course (single day per week)'), ('multicourse', 'Course (multiple days per week)'), ('camp', 'Camp')], db_index=True, default='course', max_length=30, verbose_name='Course type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='visible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Course visible'),
        ),
    ]
