# Generated by Django 3.2.25 on 2025-11-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0032_course_has_waiting_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesinstructors',
            name='contract_number',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True, verbose_name='Contract number'),
        ),
    ]
