# Generated by Django 3.2.25 on 2025-12-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0033_coursesinstructors_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesinstructors',
            name='contract_number',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Contract number'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesinstructors',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursesinstructors',
            constraint=models.UniqueConstraint(fields=('course', 'instructor'), name='unique_course_instructor'),
        ),
        migrations.AddConstraint(
            model_name='coursesinstructors',
            constraint=models.UniqueConstraint(condition=models.Q(('contract_number__isnull', True), _negated=True), fields=('instructor', 'function', 'contract_number'), name='unique_contract_per_instructor_function'),
        ),
    ]
