# Generated by Django 3.2.25 on 2025-12-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0034_auto_20251201_1117'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursesinstructors',
            name='unique_contract_per_instructor_function',
        ),
        migrations.AddConstraint(
            model_name='coursesinstructors',
            constraint=models.UniqueConstraint(condition=models.Q(('contract_number__isnull', True), _negated=True), fields=('instructor', 'function'), name='unique_instructor_function_single_contract_number'),
        ),
    ]
