# Generated by Django 3.2.25 on 2025-12-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0036_auto_20251201_1141'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursesinstructors',
            name='unique_instructor_function_contract_number',
        ),
    ]
