# Generated by Django 3.2.25 on 2026-07-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0037_remove_coursesinstructors_unique_instructor_function_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_family_3rd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applied for the third and following members registered to the same course', max_digits=5, null=True, verbose_name='Price for family members (3rd child and following)'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_local_family_3rd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applied for the third and following members registered to the same course if the family is local', max_digits=5, null=True, verbose_name='Price for local family members (3rd child and following)'),
        ),
    ]
