# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyuser',
            name='billing_identifier',
        ),
        migrations.RemoveField(
            model_name='familyuser',
            name='finished_registration',
        ),
        migrations.RemoveField(
            model_name='familyuser',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='familyuser',
            name='total',
        ),
    ]
