# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        ('activities', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='courses',
            field=models.ManyToManyField(through='registrations.Registration', to='activities.Course'),
        ),
    ]
