# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 07:02
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyuser',
            options={'get_latest_by': 'date_joined', 'ordering': ('last_name', 'first_name'), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
