# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 07:35
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_school_year_add_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolyear",
            name="year",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1P"),
                    (2, "2P"),
                    (3, "3P"),
                    (4, "4P"),
                    (5, "5P"),
                    (6, "6P"),
                    (7, "7P"),
                    (8, "8P"),
                    (9, "9S"),
                    (10, "10S"),
                    (11, "11S"),
                    (12, "12S"),
                ],
                unique=True,
                verbose_name="School year",
            ),
        ),
    ]
