# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-26 16:22
from django.db import migrations

import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_auto_20170906_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyuser",
            name="iban",
            field=localflavor.generic.models.IBANField(
                blank=True,
                include_countries=(
                    "AT",
                    "BE",
                    "BG",
                    "CH",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GI",
                    "GR",
                    "HR",
                    "HU",
                    "IE",
                    "IS",
                    "IT",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "NL",
                    "NO",
                    "PL",
                    "PT",
                    "RO",
                    "SE",
                    "SI",
                    "SK",
                    "SM",
                ),
                max_length=34,
                use_nordea_extensions=False,
            ),
        ),
    ]
