# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-26 16:22
from __future__ import unicode_literals

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170906_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyuser',
            name='iban',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=(b'AT', b'BE', b'BG', b'CH', b'CY', b'CZ', b'DE', b'DK', b'EE', b'ES', b'FI', b'FR', b'GB', b'GI', b'GR', b'HR', b'HU', b'IE', b'IS', b'IT', b'LI', b'LT', b'LU', b'LV', b'MC', b'MT', b'NL', b'NO', b'PL', b'PT', b'RO', b'SE', b'SI', b'SK', b'SM'), max_length=34, use_nordea_extensions=False),
        ),
    ]
