# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_familyuser_js_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code name'),
        ),
    ]
