# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-09 16:06
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_school_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("zipcode", models.CharField(max_length=5, verbose_name="NPA")),
                ("name", models.CharField(max_length=100, verbose_name="City")),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("CH", "Switzerland"),
                            ("FL", "Liechtenstein"),
                            ("D", "Germany"),
                            ("F", "France"),
                            ("I", "Italy"),
                            ("A", "Austria"),
                        ],
                        default="CH",
                        max_length=2,
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "ordering": ("zipcode", "name"),
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
    ]
