# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 13:05
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
