# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 14:43
from __future__ import absolute_import, unicode_literals

import uuid

from django.db import migrations, models


def fill_family_uuid(apps, schema_editor):
    FamilyUser = apps.get_model("profiles", "FamilyUser")
    for obj in FamilyUser.objects.using("default").all():
        obj.uuid = uuid.uuid4()
        obj.save()


def fill_is_manager(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    try:
        managers = Group.objects.get(name="Sports managers")
    except Group.DoesNotExist:
        return
    for obj in managers.user_set.all():
        obj.is_manager = True
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_auto_20200612_1505"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyuser",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(fill_family_uuid, migrations.RunPython.noop),
        migrations.AddField(
            model_name="familyuser",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="Is manager"),
        ),
        migrations.RunPython(fill_is_manager, migrations.RunPython.noop),
    ]
