# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 16:09
from __future__ import unicode_literals
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_add_uuid'),
        ('absences', '0013_session_instructor_uuid'),
        ('activities', '0022_instructors_uuid'),
        ('registrations', '0035_add_uuid_to_family'),

    ]

    operations = [
        migrations.RemoveField('FamilyUser', 'id'),
        migrations.RenameField(
            model_name='familyuser',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='familyuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
