# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 07:47
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_switch_pk_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyuser',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='familyuser',
            name='created_on',
            field=models.CharField(blank=True, default='local', editable=False, max_length=255, verbose_name='Instance name'),
        ),
        migrations.AddField(
            model_name='familyuser',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
