# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 10:48
from __future__ import unicode_literals

from django.db import migrations

DROP_HISTORY = 'TRUNCATE TABLE "public"."django_admin_log" CASCADE;'
ALTER_HISTORY1 = 'ALTER TABLE "public"."django_admin_log" DROP COLUMN "user_id";'
ALTER_HISTORY2 = 'ALTER TABLE "public"."django_admin_log" ADD COLUMN "user_id" uuid;'
ALTER_HISTORY3 = 'CREATE INDEX "django_admin_user_id" ON "public"."django_admin_log"("user_id");'


DROP_GROUP = 'TRUNCATE TABLE "public"."profiles_familyuser_groups" CASCADE;'
ALTER_GROUP1 = 'ALTER TABLE "public"."profiles_familyuser_groups" DROP COLUMN "familyuser_id";'
ALTER_GROUP2 = 'ALTER TABLE "public"."profiles_familyuser_groups" ADD COLUMN "familyuser_id" uuid;'
ALTER_GROUP3 = 'CREATE INDEX "profiles_familyuser_groups_user_id" ON "public"."profiles_familyuser_groups"("familyuser_id");'
ALTER_GROUP4 = 'CREATE INDEX "profiles_familyuser_groups_user_id_group_id" ON "public"."profiles_familyuser_groups"("familyuser_id","group_id");'

DROP_USER_PERMISSIONS = 'TRUNCATE TABLE "public"."profiles_familyuser_user_permissions" CASCADE;'
ALTER_USER_PERMISSIONS1 = 'ALTER TABLE "public"."profiles_familyuser_user_permissions" DROP COLUMN "familyuser_id";'
ALTER_USER_PERMISSIONS2 = 'ALTER TABLE "public"."profiles_familyuser_user_permissions" ADD COLUMN "familyuser_id" uuid;'
ALTER_USER_PERMISSIONS3 = 'CREATE INDEX "profiles_familyuser_user_permissions_user_id" ON "public"."profiles_familyuser_user_permissions"("familyuser_id");'
ALTER_USER_PERMISSIONS4 = 'CREATE INDEX "profiles_familyuser_user_permissions_user_id_permission_id" ON "public"."profiles_familyuser_user_permissions"("familyuser_id","permission_id");'


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20200716_0947'),
    ]

    operations = [
        migrations.RunSQL(DROP_HISTORY),
        migrations.RunSQL(ALTER_HISTORY1),
        migrations.RunSQL(ALTER_HISTORY2),
        migrations.RunSQL(ALTER_HISTORY3),

        migrations.RunSQL(DROP_GROUP),
        migrations.RunSQL(ALTER_GROUP1),
        migrations.RunSQL(ALTER_GROUP2),
        migrations.RunSQL(ALTER_GROUP3),
        migrations.RunSQL(ALTER_GROUP4),

        migrations.RunSQL(DROP_USER_PERMISSIONS),
        migrations.RunSQL(ALTER_USER_PERMISSIONS1),
        migrations.RunSQL(ALTER_USER_PERMISSIONS2),
        migrations.RunSQL(ALTER_USER_PERMISSIONS3),
        migrations.RunSQL(ALTER_USER_PERMISSIONS4),
    ]
