# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-21 13:36
from django.db import migrations, models

import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_auto_20200812_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyuser",
            name="bank_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Bank name"),
        ),
        migrations.AddField(
            model_name="familyuser",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("f", "Female"), ("m", "Male")], max_length=1
            ),
        ),
        migrations.AddField(
            model_name="familyuser",
            name="is_mep",
            field=models.BooleanField(default=False, verbose_name="Is sports teacher"),
        ),
        migrations.AddField(
            model_name="familyuser",
            name="is_teacher",
            field=models.BooleanField(default=False, verbose_name="Is teacher"),
        ),
        migrations.AddField(
            model_name="familyuser",
            name="nationality",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, verbose_name="Nationality"
            ),
        ),
        migrations.AddField(
            model_name="familyuser",
            name="permit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L", "L - Short-term residence permit"),
                    ("", "B - Residence permit"),
                    ("C", "C - Settlement permit"),
                    ("Ci", "Ci - Residence permit with gainful employment"),
                    ("G", "G - Cross-border commuter permit"),
                    ("F", "F - Provisionally admitted foreigners"),
                    ("N", "N - Permit for asylum-seekers"),
                    ("S", "S - People in need of protection"),
                ],
                max_length=2,
                null=True,
                verbose_name="Permit type",
            ),
        ),
    ]
