# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-21 13:36
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20200812_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank name'),
        ),
        migrations.AddField(
            model_name='familyuser',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'f', 'Female'), (b'm', 'Male')], max_length=1),
        ),
        migrations.AddField(
            model_name='familyuser',
            name='is_mep',
            field=models.BooleanField(default=False, verbose_name='Is sports teacher'),
        ),
        migrations.AddField(
            model_name='familyuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Is teacher'),
        ),
        migrations.AddField(
            model_name='familyuser',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='familyuser',
            name='permit_type',
            field=models.CharField(blank=True, choices=[(b'L', 'L - Short-term residence permit'), (b'B', 'B - Residence permit'), (b'C', 'C - Settlement permit'), (b'Ci', 'Ci - Residence permit with gainful employment'), (b'G', 'G - Cross-border commuter permit'), (b'F', 'F - Provisionally admitted foreigners'), (b'N', 'N - Permit for asylum-seekers'), (b'S', 'S - People in need of protection')], max_length=2, null=True, verbose_name='Permit type'),
        ),
    ]
