# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-30 08:33
from __future__ import absolute_import, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_auto_20210621_1536"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={
                "ordering": ("name",),
                "verbose_name": "school",
                "verbose_name_plural": "schools",
            },
        ),
    ]
