# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-10 05:16
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_auto_20210730_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyuser",
            name="external_identifier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Identifier"
            ),
        ),
    ]
