# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [ ('profiles', '0019_auto_20160421_1341'),]

    database_operations = [
        migrations.AlterModelTable('Registration', 'registrations_registration'),
        migrations.AlterModelTable('ExtraInfo', 'registrations_extrainfo'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='child',
            name='courses',
        ),
        migrations.DeleteModel('Registration'),
        migrations.DeleteModel('ExtraInfo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]