# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20160421_1341'),
        ('registrations', '0001_initial'),
        ('profiles', '0020_move_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='courses',
            field=models.ManyToManyField(through='registrations.Registration', to='activities.Course'),
        ),
    ]
