# Generated by Django 3.2.16 on 2023-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_familyuser_permit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male')], max_length=1, verbose_name='Gender'),
        ),
    ]
