# Generated by Django 3.2.20 on 2023-10-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_familyuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyuser',
            name='country',
            field=models.CharField(blank=True, choices=[('CH', 'Switzerland'), ('FL', 'Liechtenstein'), ('D', 'Germany'), ('F', 'France'), ('I', 'Italy'), ('A', 'Austria')], default='CH', max_length=2, verbose_name='Country'),
        ),
    ]
