# Generated by Django 3.2.20 on 2024-03-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_familyuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyuser',
            name='is_restricted_manager',
            field=models.BooleanField(default=False, verbose_name='Is restricted manager'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, '1H'), (2, '2H'), (3, '3H'), (4, '4H'), (5, '5H'), (6, '6H'), (7, '7H'), (8, '8H'), (9, '9H'), (10, '10H'), (11, '11H'), (12, '12H')], unique=True, verbose_name='School year'),
        ),
    ]
