# Generated by Django 3.2.25 on 2025-08-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_add_is_restricted_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, '1P'), (2, '2P'), (3, '3P'), (4, '4P'), (5, '5P'), (6, '6P'), (7, '7P'), (8, '8P'), (9, '9S'), (10, '10S'), (11, '11S'), (12, '12R')], unique=True, verbose_name='School year'),
        ),
    ]
