# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 10:43
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatranstransaction",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datatrans_transactions",
                to="registrations.Bill",
            ),
        ),
        migrations.AlterField(
            model_name="datatranstransaction",
            name="transaction_id",
            field=models.BigIntegerField(),
        ),
    ]
