# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210409_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatranstransaction',
            options={'ordering': ('-expiration',)},
        ),
        migrations.AlterField(
            model_name='datatranstransaction',
            name='transaction_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
