# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-18 09:25
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210414_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatranstransaction',
            name='payment_method',
            field=models.CharField(choices=[('AZP', 'Amazon Pay'), ('AMX', 'American Express'), ('APL', 'Apple Pay'), ('PAY', 'Google Pay'), ('KLN', 'Klarna'), ('MAU', 'Maestro'), ('ECA', 'Mastercard'), ('PAP', 'PayPal'), ('PFC', 'PostFinance Card'), ('PEF', 'PostFinance E-Finance'), ('REK', 'Reka'), ('SAM', 'Samsung Pay'), ('ESY', 'Swisscom Pay'), ('TWI', 'Twint'), ('VIS', 'Visa')], default='TWI', max_length=3),
        ),
    ]
