# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-18 14:05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_datatranstransaction_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatranstransaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("AZP", "Amazon Pay"),
                    ("AMX", "American Express"),
                    ("APL", "Apple Pay"),
                    ("PAY", "Google Pay"),
                    ("KLN", "Klarna"),
                    ("MAU", "Maestro"),
                    ("ECA", "Mastercard"),
                    ("PAP", "PayPal"),
                    ("PFC", "PostFinance Card"),
                    ("PEF", "PostFinance E-Finance"),
                    ("REK", "Reka"),
                    ("SAM", "Samsung Pay"),
                    ("ESY", "Swisscom Pay"),
                    ("TWI", "Twint"),
                    ("VIS", "Visa"),
                    ("cash", "Cash"),
                ],
                default="TWI",
                max_length=3,
            ),
        ),
    ]
