# Generated by Django 3.2.21 on 2023-11-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_postfinancetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfinancetransaction',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='postfinancetransaction',
            name='webhook',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
