# Generated by Django 3.2.20 on 2023-11-08 20:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20231108_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfinancetransaction',
            name='webhook',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
