# Generated by Django 3.2.25 on 2025-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_postfinancetransaction_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatranstransaction',
            name='transaction_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
