# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 08:15
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# registrations.migrations.0014_data_add_transport
# registrations.migrations.0021_copy_levels_from_registrations
# registrations.migrations.0034_dm_initial_profiles
# registrations.migrations.0035_add_uuid_to_family

class Migration(migrations.Migration):

    replaces = [(b'registrations', '0001_initial'), (b'registrations', '0002_add_bills'), (b'registrations', '0003_auto_20160520_1535'), (b'registrations', '0004_auto_20160608_1757'), (b'registrations', '0005_add_school'), (b'registrations', '0006_child_emergency_number'), (b'registrations', '0007_auto_20160817_0706'), (b'registrations', '0008_default_extraneed_value'), (b'registrations', '0009_auto_20161201_1200'), (b'registrations', '0010_child_bib_number'), (b'registrations', '0011_registration_transport_info'), (b'registrations', '0012_add_levels'), (b'registrations', '0013_add_transport'), (b'registrations', '0014_data_add_transport'), (b'registrations', '0015_remove_registration_transport_info'), (b'registrations', '0016_auto_20170120_1838'), (b'registrations', '0017_auto_20170324_1331'), (b'registrations', '0018_auto_20170821_1151'), (b'registrations', '0019_auto_20170906_1332'), (b'registrations', '0020_child_activity_level_model'), (b'registrations', '0021_copy_levels_from_registrations'), (b'registrations', '0022_remove_note_and_levels_from_registration'), (b'registrations', '0023_auto_20180126_1722'), (b'registrations', '0024_child_building'), (b'registrations', '0025_auto_20180808_1112'), (b'registrations', '0026_bill_reminder_sent'), (b'registrations', '0027_bill_reminder_sent_date'), (b'registrations', '0028_auto_20181119_0621'), (b'registrations', '0029_auto_20190305_0533'), (b'registrations', '0030_auto_20190315_1758'), (b'registrations', '0031_auto_20200108_1151'), (b'registrations', '0032_auto_20200608_0741'), (b'registrations', '0033_registrationsprofile'), (b'registrations', '0034_dm_initial_profiles'), (b'registrations', '0035_add_uuid_to_family'), (b'registrations', '0036_replace_fk_to_family'), (b'registrations', '0037_auto_20200812_1403')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_squashed_0023_remove_course_instructors'),
        ('schools', '0003_auto_20180720_1606'),
        ('profiles', '0014_switch_pk_to_uuid'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('nationality', models.CharField(choices=[('CH', 'Swiss'), ('FL', 'Liechtenstein'), ('DIV', 'Other')], default='CH', max_length=3)),
                ('language', models.CharField(choices=[('D', 'Deutsch'), ('E', 'English'), ('F', 'Fran\xe7ais'), ('I', 'Italiano')], default='F', max_length=2)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.ExtraNeed')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('waiting', "Waiting parent's confirmation"), ('valid', 'Validated by parent'), ('canceled', 'Canceled by administrator'), ('confirmed', 'Confirmed by administrator')], default='waiting', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registrations.Child')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.Course', verbose_name='Course')),
                ('paid', models.BooleanField(default=False, verbose_name='Has paid')),
                ('transport_info', models.CharField(blank=True, max_length=60, verbose_name='Transport information')),
                ('after_level', models.CharField(blank=True, choices=[('NP', 'NP'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='End course level')),
                ('before_level', models.CharField(blank=True, choices=[('NP', 'NP'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='Level -1')),
            ],
            options={
                'ordering': ('child__last_name', 'child__first_name', 'course__start_date'),
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_infos', to='registrations.Registration'),
        ),
        migrations.AddField(
            model_name='child',
            name='courses',
            field=models.ManyToManyField(through='registrations.Registration', to=b'activities.Course'),
        ),
        migrations.AddField(
            model_name='child',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.SchoolYear'),
        ),
        migrations.AddField(
            model_name='child',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('course', 'child', 'status')]),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[(0, 'dummy')], default='just_created', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('billing_identifier', models.CharField(blank=True, max_length=45, verbose_name='Billing identifier')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total to be paid')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='id_lagapeo',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Lagapeo Identification number'),
        ),
        migrations.AddField(
            model_name='child',
            name='other_school',
            field=models.CharField(blank=True, max_length=50, verbose_name='Other school'),
        ),
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='profiles.School'),
        ),
        migrations.AddField(
            model_name='child',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Emergency number'),
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelOptions(
            name='extrainfo',
            options={'ordering': ('key', 'registration')},
        ),
        migrations.AddField(
            model_name='child',
            name='bib_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bib number'),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='Label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='registration',
            name='transport_info',
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Transport', 'verbose_name_plural': 'Transports'},
        ),
        migrations.AddField(
            model_name='registration',
            name='note',
            field=models.CharField(blank=True, max_length=50, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='after_level',
            field=models.CharField(blank=True, choices=[('NP', 'NP'), ('CM', 'CM'), ('ABS', 'ABS'), ('NPA', 'NPA'), ('NPB', 'NPB'), ('NPC', 'NPC'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='End course level'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='before_level',
            field=models.CharField(blank=True, choices=[('NP', 'NP'), ('CM', 'CM'), ('ABS', 'ABS'), ('NPA', 'NPA'), ('NPB', 'NPB'), ('NPC', 'NPC'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='Level -1'),
        ),
        migrations.AlterField(
            model_name='child',
            name='emergency_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, verbose_name='Emergency number'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='profiles.School'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.SchoolYear'),
        ),
        migrations.AddField(
            model_name='registration',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='registrations.Bill'),
        ),
        migrations.AddField(
            model_name='registration',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='registrations.Transport', verbose_name='Transport information'),
        ),
        migrations.CreateModel(
            name='ChildActivityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('before_level', models.CharField(blank=True, choices=[('NP', 'NP'), ('CM', 'CM'), ('ABS', 'ABS'), ('NPA', 'NPA'), ('NPB', 'NPB'), ('NPC', 'NPC'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='Level -1')),
                ('after_level', models.CharField(blank=True, choices=[('NP', 'NP'), ('CM', 'CM'), ('ABS', 'ABS'), ('NPA', 'NPA'), ('NPB', 'NPB'), ('NPC', 'NPC'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='End course level')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='Note')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='activities.Activity', verbose_name='Course')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='registrations.Child')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='childactivitylevel',
            unique_together=set([('activity', 'child')]),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='after_level',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='before_level',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='note',
        ),
        migrations.AddField(
            model_name='child',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.Building'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='profiles.School'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.SchoolYear'),
        ),
        migrations.AlterField(
            model_name='child',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.Teacher'),
        ),
        migrations.AddField(
            model_name='bill',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Reminder sent'),
        ),
        migrations.AddField(
            model_name='bill',
            name='reminder_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reminder sent date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='registrations.Transport', verbose_name='Transport information'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='registrations.Transport', verbose_name='Transport information'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='registrations.Transport', verbose_name='Transport information'),
        ),
        migrations.AlterField(
            model_name='childactivitylevel',
            name='before_level',
            field=models.CharField(blank=True, max_length=10, verbose_name='Level -1'),
        ),
        migrations.AddField(
            model_name='child',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='updated', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='child',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.CreateModel(
            name='RegistrationsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('has_paid_all', models.BooleanField(default=False, editable=False)),
                ('finished_registering', models.BooleanField(default=False, editable=False)),
                ('last_registration', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationsprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile',
                                       to=settings.AUTH_USER_MODEL),
        ),

    ]
