# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 16:09
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('activities', '0002_course_responsible'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('nationality', models.CharField(choices=[('CH', 'Swiss'), ('FL', 'Liechtenstein'), ('DIV', 'Other')], default='CH', max_length=3)),
                ('language', models.CharField(choices=[('D', 'Deutsch'), ('E', 'English'), ('F', 'Fran\xe7ais'), ('I', 'Italiano')], default='F', max_length=2)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.ExtraNeed')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('waiting', "Waiting parent's confirmation"), ('valid', 'Validated by parent'), ('canceled', 'Canceled by administrator'), ('confirmed', 'Confirmed by administrator')], default='waiting', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registrations.Child')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.Course', verbose_name='Course')),
            ],
            options={
                'ordering': ('child__last_name', 'child__first_name', 'course__start_date'),
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_infos', to='registrations.Registration'),
        ),
        migrations.AddField(
            model_name='child',
            name='courses',
            field=models.ManyToManyField(through='registrations.Registration', to='activities.Course'),
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.SchoolYear'),
        ),
        migrations.AddField(
            model_name='child',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('course', 'child')]),
        ),
    ]
