# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 13:35
from django.db import migrations

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_add_bills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[(0, "dummy")],
                default="just_created",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
    ]
