# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 14:30
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20210414_1630'),
        ('registrations', '0002_auto_20210413_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='allocation_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='activities.AllocationAccount', verbose_name='Allocation account'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('datatrans', 'immediate with credit card (datatrans)'), ('iban', 'Later with wire transfer')], max_length=20, verbose_name='Payment method'),
        ),
    ]
