# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 15:57
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20160520_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='id_lagapeo',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Lagapeo Identification number'),
        ),
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='child',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.SchoolYear'),
        ),
    ]
