# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 14:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_auto_20210414_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="price",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
