# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school'),
        ('registrations', '0004_auto_20160608_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='other_school',
            field=models.CharField(blank=True, max_length=50, verbose_name='Other school'),
        ),
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.School'),
        ),
    ]
