# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 14:49
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_school"),
        ("registrations", "0004_auto_20160608_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="other_school",
            field=models.CharField(blank=True, max_length=50, verbose_name="Other school"),
        ),
        migrations.AddField(
            model_name="child",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="profiles.School",
            ),
        ),
    ]
