# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-07 14:44
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registration_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
