# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 10:19
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_add_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Emergency number'),
        ),
    ]
