# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-19 08:00
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0006_auto_20210604_1643"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={
                "ordering": ("-created",),
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
            },
        ),
        migrations.AddField(
            model_name="child",
            name="is_blacklisted",
            field=models.BooleanField(default=False, verbose_name="Is blacklisted", db_index=True),
        ),
    ]
