# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 05:06
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_child_emergency_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('course', 'child', 'status')]),
        ),
    ]
