# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-23 09:05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0007_auto_20210719_1000"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="confirmation_sent_on",
            field=models.DateField(null=True, verbose_name="Confirmation mail sent on"),
        ),
    ]
