# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 05:18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0007_auto_20160817_0706"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={"verbose_name": "Bill", "verbose_name_plural": "Bills"},
        ),
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name": "Child", "verbose_name_plural": "Children"},
        ),
        migrations.AlterField(
            model_name="extrainfo",
            name="value",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
