# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_registration_confirmation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('iban', 'Later with wire transfer'), ('datatrans', 'immediate with credit card (datatrans)')], max_length=20, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='confirmation_sent_on',
            field=models.DateField(blank=True, null=True, verbose_name='Confirmation mail sent on'),
        ),
    ]
