# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 11:00
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_default_extraneed_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrainfo',
            options={'ordering': ('key', 'registration')},
        ),
    ]
