# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20161201_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='bib_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bib number'),
        ),
    ]
