# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-18 07:47
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0010_child_bib_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="transport_info",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Transport information"
            ),
        ),
    ]
