# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-18 14:05
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_registration_cancelation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='avs',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='AVS'),
        ),
    ]
