# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 06:49
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_child_avs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsprofile',
            name='has_paid_all',
            field=models.BooleanField(default=False),
        ),
    ]
