# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-13 08:47
import django.db.models.deletion
from django.db import migrations, models


def move_transport_info(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Registration = apps.get_model("registrations", "Registration")
    Transport = apps.get_model("registrations", "Transport")

    for registration in Registration.objects.all():
        if registration.transport_info:
            transport, created = Transport.objects.get_or_create(name=registration.transport_info)
            registration.transport = transport
            registration.save()


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0013_add_transport"),
    ]

    operations = [migrations.RunPython(move_transport_info)]
