# Generated by Django 3.2.16 on 2022-12-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_alter_activity_allocation_account'),
        ('registrations', '0014_auto_20221108_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='allocation_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='activities.allocationaccount', verbose_name='Allocation account'),
        ),
        migrations.AlterField(
            model_name='registrationsprofile',
            name='finished_registering',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='registrationsprofile',
            name='has_paid_all',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
