# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_remove_registration_transport_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Transport', 'verbose_name_plural': 'Transports'},
        ),
        migrations.AddField(
            model_name='registration',
            name='note',
            field=models.CharField(blank=True, max_length=50, verbose_name='Note'),
        ),
    ]
