# Generated by Django 3.2.16 on 2023-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_auto_20221215_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due date'),
        ),
    ]
