# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-24 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_auto_20170120_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='after_level',
            field=models.CharField(blank=True, choices=[('NP', 'NP'), ('CM', 'CM'), ('ABS', 'ABS'), ('NPA', 'NPA'), ('NPB', 'NPB'), ('NPC', 'NPC'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='End course level'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='before_level',
            field=models.CharField(blank=True, choices=[('NP', 'NP'), ('CM', 'CM'), ('ABS', 'ABS'), ('NPA', 'NPA'), ('NPB', 'NPB'), ('NPC', 'NPC'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='Level -1'),
        ),
    ]
