# Generated by Django 3.2.16 on 2023-06-13 07:45

from django.db import migrations
from dateutil.relativedelta import relativedelta

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    from dynamic_preferences.registries import global_preferences_registry
    Bill = apps.get_model('registrations', 'Bill')
    global_preferences = global_preferences_registry.manager()
    delay = global_preferences["payment__DELAY_DAYS"]

    for bill in Bill.objects.all():
        if not bill.due_date:
            bill.due_date = bill.created + relativedelta(days=delay)
            bill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_bill_due_date'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
