# Generated by Django 3.2.16 on 2023-07-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_dm_due_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('iban', 'Later with wire transfer'), ('datatrans', 'immediate with credit card (datatrans)'), ('postfinance', 'immediate with credit card (postfinance)')], max_length=20, verbose_name='Payment method'),
        ),
    ]
