# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-21 09:51
from __future__ import absolute_import, unicode_literals

from django.db import migrations

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0017_auto_20170324_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="emergency_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=30, verbose_name="Emergency number"
            ),
        ),
    ]
