# Generated by Django 3.2.20 on 2023-10-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_alter_bill_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='extra_infos'),
        ),
    ]
