# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-06 11:32
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_auto_20170821_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='profiles.School'),
        ),
        migrations.AlterField(
            model_name='child',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.SchoolYear'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='registrations.Bill'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='registrations.Transport', verbose_name='Transport information'),
        ),
    ]
