# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-29 15:23
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_auto_20170728_1716'),
        ('registrations', '0019_auto_20170906_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildActivityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('before_level', models.CharField(blank=True, choices=[('NP', 'NP'), ('CM', 'CM'), ('ABS', 'ABS'), ('NPA', 'NPA'), ('NPB', 'NPB'), ('NPC', 'NPC'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='Level -1')),
                ('after_level', models.CharField(blank=True, choices=[('NP', 'NP'), ('CM', 'CM'), ('ABS', 'ABS'), ('NPA', 'NPA'), ('NPB', 'NPB'), ('NPC', 'NPC'), ('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C'), ('5A', '5A'), ('5B', '5B'), ('5C', '5C'), ('6A', '6A'), ('6B', '6B'), ('6C', '6C'), ('7A', '7A'), ('7B', '7B'), ('7C', '7C')], max_length=5, verbose_name='End course level')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='Note')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='activities.Activity', verbose_name='Course')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='registrations.Child')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='childactivitylevel',
            unique_together=set([('activity', 'child')]),
        ),
    ]
