# Generated by Django 3.2.20 on 2023-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_extrainfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Has been paid'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
