# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-29 15:24
from __future__ import unicode_literals

from django.db import migrations


def forwards_copy(apps, schema_editor):
    Registration = apps.get_model('registrations', 'Registration')
    ChildActivityLevel = apps.get_model('registrations', 'ChildActivityLevel')
    for registration in Registration.objects.order_by('modified'):
        if registration.before_level or registration.after_level or registration.note:
            defaults = {}
            if registration.before_level:
                defaults['before_level'] = registration.before_level
            if registration.after_level:
                defaults['after_level'] = registration.after_level
            if registration.note:
                defaults['note'] = registration.note
            ChildActivityLevel.objects.update_or_create(activity=registration.course.activity,
                                                        child=registration.child,
                                                        defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0020_child_activity_level_model'),
    ]

    operations = [
        migrations.RunPython(forwards_copy)
    ]
