# Generated by Django 3.2.20 on 2024-06-25 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0021_alter_bill_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cancelation_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cancelation_reason',
            field=models.CharField(blank=True, choices=[('expired', 'Expired'), ('admin', 'Admin'), ('instructor', 'Instructor'), ('moved', 'Moved to another course')], db_index=True, max_length=20, null=True, verbose_name='Cancelation reason'),
        ),
    ]
