# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-29 15:35
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0021_copy_levels_from_registrations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="after_level",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="before_level",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="note",
        ),
    ]
