# Generated by Django 3.2.20 on 2024-06-25 15:43

from django.db import migrations, models



def set_cancelation_date(apps, schema_editor):
    Registration = apps.get_model('registrations', 'Registration')
    for registration in Registration.objects.filter(status='canceled'):
        registration.cancelation_date = registration.modified
        registration.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_add_cancel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cancelation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelation date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cancelation_reason',
            field=models.CharField(blank=True, choices=[('expired', 'Expired'), ('admin', 'Manager decision'), ('instructor', 'Instructor decision'), ('moved', 'Moved to another course')], db_index=True, max_length=20, null=True, verbose_name='Cancelation reason'),
        ),
        migrations.RunPython(set_cancelation_date),
    ]
