# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-26 16:22
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0022_remove_note_and_levels_from_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
