# Generated by Django 3.2.20 on 2024-08-05 07:50

from django.db import migrations, models


def set_payment_date(apps, schema_editor):
    Bill = apps.get_model('registrations', 'Bill')
    for bill in Bill.objects.filter(status='paid'):
        bill.payment_date = bill.modified
        bill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_add_cancelation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.RunPython(set_payment_date),
    ]
