# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-20 14:06
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_auto_20180720_1606"),
        ("registrations", "0023_auto_20180126_1722"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="building",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="schools.Building",
            ),
        ),
    ]
