# Generated by Django 3.2.20 on 2024-08-06 13:53

from django.db import migrations


def update_payment_method(apps, schema_editor):
    Bill = apps.get_model('registrations', 'Bill')
    Bill.objects.filter(payment_method='wire_transfer').update(payment_method='iban')


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_bill_payment_date'),
    ]

    operations = [
        migrations.RunPython(update_payment_method),
    ]
