# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-08 09:12
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0024_child_building"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="schools.Building",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="profiles.School",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.SchoolYear",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="schools.Teacher",
            ),
        ),
    ]
