# Generated by Django 3.2.25 on 2024-10-11 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0025_dm_remove_wire_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2024, 10, 11, 16, 3, 53, 474080, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('iban', 'Wire transfer'), ('datatrans', 'Credit card (datatrans)'), ('postfinance', 'Credit card (postfinance)'), ('on-site', 'On-Site payment'), ('external', 'External invoice')], max_length=20, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_infos', to='registrations.registration', verbose_name='Registration'),
        ),
    ]
