# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 19:34
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0026_bill_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="reminder_sent_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Reminder sent date"),
        ),
    ]
