# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0027_bill_reminder_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='registrations.Transport', verbose_name='Transport information'),
        ),
    ]
