# Generated by Django 3.2.25 on 2024-11-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0027_registrationvalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationvalidation',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='registrations.bill'),
        ),
    ]
