# Generated by Django 3.2.25 on 2025-08-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0029_auto_20250410_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='do_not_expire',
            field=models.BooleanField(default=False, verbose_name='Do not expire'),
        ),
    ]
