# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-15 16:58
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0029_auto_20190305_0533"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="transport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participants",
                to="registrations.Transport",
                verbose_name="Transport information",
            ),
        ),
    ]
