# Generated by Django 3.2.25 on 2025-08-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0030_bill_do_not_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Last name'),
        ),
    ]
