# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-08 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0030_auto_20190315_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childactivitylevel',
            name='before_level',
            field=models.CharField(blank=True, max_length=10, verbose_name='Level -1'),
        ),
    ]
