# Generated by Django 3.2.25 on 2025-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0031_alter_child_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
    ]
