# Generated by Django 3.2.25 on 2026-08-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0032_alter_child_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='qr_invoice',
            field=models.TextField(blank=True, default='', verbose_name='QR invoice'),
        ),
    ]
