# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 13:05
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registrations", "0032_auto_20200608_0741"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationsProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("has_paid_all", models.BooleanField(default=False, editable=False)),
                ("finished_registering", models.BooleanField(default=False, editable=False)),
                ("last_registration", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
