# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 13:06
from __future__ import unicode_literals

from django.db import migrations

from profiles.models import FamilyUser


def forward(apps, schema_editor):
    RegistrationsProfile = apps.get_model('registrations', 'RegistrationsProfile')
    FamilyUser = apps.get_model('profiles', 'FamilyUser')
    for user in FamilyUser.objects.all():
        RegistrationsProfile.objects.get_or_create(user=user)


def backward(apps, schema_editor):
    RegistrationsProfile = apps.get_model('registrations', 'RegistrationsProfile')
    RegistrationsProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0033_registrationsprofile'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
