# Generated by Django 3.2.25 on 2026-08-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0033_bill_qr_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='bills/', verbose_name='PDF'),
        ),
    ]
