# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 15:44
from __future__ import unicode_literals

from __future__ import absolute_import
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def fill_bill_family_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Bill = apps.get_model('registrations', 'Bill')
    for obj in Bill.objects.using(db_alias).select_related('family').exclude(family__isnull=True):
        obj.family_uuid = obj.family.uuid
        obj.save()


def revert_fill_bill_family_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Bill = apps.get_model('registrations', 'Bill')
    FamilyUser = apps.get_model('profiles', 'FamilyUser')
    for obj in Bill.objects.using(db_alias).select_related('family').exclude(family_uuid__isnull=True):
        obj.family = FamilyUser.objects.get(uuid=obj.family_uuid)
        obj.save()


def fill_child_family_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Child = apps.get_model('registrations', 'Child')
    for obj in Child.objects.using(db_alias).select_related('family').exclude(family__isnull=True):
        obj.family_uuid = obj.family.uuid
        obj.save()


def revert_fill_child_family_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Child = apps.get_model('registrations', 'Child')
    FamilyUser = apps.get_model('profiles', 'FamilyUser')
    for obj in Child.objects.using(db_alias).select_related('family').exclude(family_uuid__isnull=True):
        obj.family = FamilyUser.objects.get(uuid=obj.family_uuid)
        obj.save()


def fill_registrationsprofile_family_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    RegistrationsProfile = apps.get_model('registrations', 'RegistrationsProfile')
    for obj in RegistrationsProfile.objects.using(db_alias).select_related('user').exclude(user__isnull=True):
        obj.user_uuid = obj.user.uuid
        obj.save()


def revert_fill_registrationsprofile_family_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    RegistrationsProfile = apps.get_model('registrations', 'RegistrationsProfile')
    FamilyUser = apps.get_model('profiles', 'FamilyUser')
    for obj in RegistrationsProfile.objects.using(db_alias).select_related('family').exclude(user_uuid__isnull=True):
        obj.user = FamilyUser.objects.get(uuid=obj.user_uuid)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0034_dm_initial_profiles'),
        ('profiles', '0013_add_uuid'),

    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='family_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='family_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationsprofile',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(fill_bill_family_uuid, revert_fill_bill_family_uuid),
        migrations.RunPython(fill_child_family_uuid, revert_fill_child_family_uuid),
        migrations.RunPython(fill_registrationsprofile_family_uuid, revert_fill_registrationsprofile_family_uuid),
        migrations.RemoveField(
            model_name='bill',
            name='family',
        ),
        migrations.RemoveField(
            model_name='child',
            name='family',
        ),
        migrations.RemoveField(
            model_name='registrationsprofile',
            name='user',
        ),
    ]
