# Generated by Django 3.2.25 on 2026-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0034_alter_bill_pdf'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['child', 'status'], name='reg_child_status_idx'),
        ),
    ]
