# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 16:01
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0035_add_uuid_to_family"),
        ("profiles", "0014_switch_pk_to_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="family_uuid",
            new_name="family",
        ),
        migrations.RenameField(
            model_name="child",
            old_name="family_uuid",
            new_name="family",
        ),
        migrations.RenameField(
            model_name="registrationsprofile",
            old_name="user_uuid",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="bill",
            name="family",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registrationsprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
