# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 12:03
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0036_replace_fk_to_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationsprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
