# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='Building name')),
                ('external_id', models.CharField(blank=True, max_length=50, verbose_name='Identifier')),
                ('address', models.TextField(blank=True, verbose_name='Street')),
                ('zipcode', models.CharField(blank=True, max_length=5, verbose_name='NPA')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('country', models.CharField(choices=[('CH', 'Switzerland'), ('FL', 'Liechtenstein'), ('D', 'Germany'), ('F', 'France'), ('I', 'Italy'), ('A', 'Austria')], default='CH', max_length=2, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='buildings',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='schools.Building', verbose_name='Building'),
        ),
    ]
