# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-20 14:06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_auto_20180718_1827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="buildings",
            field=models.ManyToManyField(
                blank=True, related_name="teachers", to="schools.Building", verbose_name="Building"
            ),
        ),
    ]
