# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
