# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_domain_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeartenant',
            name='status',
            field=models.CharField(choices=[(b'creating', 'Creating period'), (b'copying', 'Copying data from previous year'), (b'ready', 'Ready to use')], default=b'creating', max_length=20),
        ),
    ]
