# Generated by Django 3.2.16 on 2022-12-15 10:45

from django.db import migrations, models

import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_auto_20160506_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="tenantpreferencemodel",
            name="name",
            field=models.CharField(db_index=True, max_length=150, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="tenantpreferencemodel",
            name="raw_value",
            field=models.TextField(blank=True, null=True, verbose_name="Raw Value"),
        ),
        migrations.AlterField(
            model_name="tenantpreferencemodel",
            name="section",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="Section Name",
            ),
        ),
        migrations.AlterField(
            model_name="yeartenant",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                max_length=63,
                unique=True,
                validators=[django_tenants.postgresql_backend.base._check_schema_name],
            ),
        ),
    ]
