# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# absences.migrations.0007_data_migration_present
# absences.migrations.0010_dm_sessions_activities
# absences.migrations.0013_session_instructor_uuid

class Migration(migrations.Migration):

    replaces = [(b'absences', '0001_initial'), (b'absences', '0002_auto_20160521_0705'), (b'absences', '0003_auto_20160601_1909'), (b'absences', '0004_session_instructor'), (b'absences', '0005_absence_notification_sent'), (b'absences', '0006_add_presence_status'), (b'absences', '0007_data_migration_present'), (b'absences', '0008_auto_20180217_0738'), (b'absences', '0009_session_activity'), (b'absences', '0010_dm_sessions_activities'), (b'absences', '0011_auto_20190102_0805'), (b'absences', '0012_auto_20190305_0533'), (b'absences', '0013_session_instructor_uuid'), (b'absences', '0014_session_instructor_uuid_as_fk')]

    initial = True

    dependencies = [
        ('registrations', '0001_squashed_0037_auto_20200812_1403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_squashed_0023_remove_course_instructors'),
        ('profiles', '0014_switch_pk_to_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late arrival')], default='absent', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Child')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activities.Course')),
            ],
            options={
                'ordering': ('date', 'course'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='absences.Session'),
        ),
        migrations.AddField(
            model_name='absence',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='present', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together=set([('child', 'session')]),
        ),

        migrations.AddField(
            model_name='session',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activities.Activity'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('date', 'course')]),
        ),

        migrations.AlterField(
            model_name='session',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activities.Activity'),
        ),
        migrations.AlterField(
            model_name='session',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activities.Activity'),
        ),
        migrations.AddField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
