# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_course_responsible'),
        ('registrations', '0003_auto_20160520_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late arrival')], default='absent', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateTimeField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Child')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
