# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 05:05
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ("date", "course")},
        ),
        migrations.AlterField(
            model_name="absence",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absences",
                to="absences.Session",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="activities.Course",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="date",
            field=models.DateField(),
        ),
    ]
