# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 07:42
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_squashed_0014_session_instructor_uuid_as_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='exported',
            field=models.BooleanField(default=False, verbose_name='Exported to payroll'),
        ),
    ]
