# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 17:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0002_auto_20160521_0705"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="absence",
            unique_together=set([("child", "session")]),
        ),
    ]
