# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 16:25
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_session_exported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='exported',
        ),
        migrations.AddField(
            model_name='session',
            name='export_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exported to payroll'),
        ),
    ]
