# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 05:59
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("absences", "0003_auto_20160601_1909"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
