# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 06:15
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0004_session_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="notification_sent",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="absence",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
