# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-29 02:44
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0005_absence_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='present', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
