# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-29 02:45
from django.db import migrations

from ..models import Absence as AbsenceModel


def add_present_status(apps, schema_editor):
    Session = apps.get_model("absences", "Session")
    Absence = apps.get_model("absences", "Absence")
    for session in Session.objects.all():
        children_in = [absence.child for absence in session.absences.all()]
        for registration in session.course.participants.all():
            if registration.child not in children_in:
                Absence.objects.create(
                    session=session,
                    child=registration.child,
                    status="present",
                    notification_sent=True,
                )
                children_in.append(registration.child)


def remove_present_status(apps, schema_editor):
    Absence = apps.get_model("absences", "Absence")
    Absence.objects.filter(status=Absence.STATUS.present).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0006_add_presence_status"),
        ("activities", "0015_auto_20170728_1716"),
    ]

    operations = [migrations.RunPython(add_present_status, remove_present_status)]
