# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-17 06:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0007_data_migration_present"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="session",
            unique_together=set([("date", "course")]),
        ),
    ]
