# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 06:59
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


def set_activity(apps, schema_editor):
    Session = apps.get_model('absences', 'Session')
    for session in Session.objects.all():
        session.activity = session.course.activity
        session.save()


def remove_activity(apps, schema_editor):
    Session = apps.get_model('absences', 'Session')
    for session in Session.objects.all():
        session.activity = None


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0009_session_activity'),
    ]

    operations = [
        migrations.RunPython(set_activity, remove_activity)
    ]
