# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 15:02
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0013_session_instructor_uuid"),
        ("profiles", "0014_switch_pk_to_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="instructor_uuid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="session",
            old_name="instructor_uuid",
            new_name="instructor",
        ),
    ]
