#!/bin/bash
# This hook is run after this virtualenv is activated.

export PYTHONPATH=/Users/grfavre/Documents/Projets/sportfac_project/sportfac
export DJANGO_SETTINGS_MODULE="sportfac.settings.local"
export DB_USER="sportfac"
export DB_PASSWORD="sportfac"
export DB_NAME="sportfac"
export SECRET_KEY="+4_n9u&3!calr+$r8o9un-tu2+#5g2@3q38qd&3*oe5!!xm#!f"

