# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import sportfac.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'sent', 'envoy\xe9'), (b'draft', 'brouillon')], default=b'sent', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('recipients', sportfac.models.ListField(verbose_name='Destinataires')),
                ('messages', sportfac.models.ListField(verbose_name='Message')),
                ('template', models.CharField(max_length=255, verbose_name='Mod\xe8le')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
