# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-06 11:32
from __future__ import unicode_literals

from django.db import migrations
import sportfac.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_mailarchive_bcc_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailarchive',
            name='bcc_recipients',
            field=sportfac.models.ListField(null=True, verbose_name='Copies cach\xe9es'),
        ),
    ]
