# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-17 10:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0001_initial'),
        ('mailer', '0005_auto_20170906_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('help_text', ckeditor.fields.RichTextField(blank=True)),
                ('body_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_body', to='dbtemplates.Template')),
                ('subject_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_subject', to='dbtemplates.Template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
