# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-17 11:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0006_genericemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericemail",
            name="subject",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
