# Generated by Django 3.2.16 on 2022-12-15 10:45

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_genericemail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailarchive',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='sent', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
