# Generated by Django 3.2.25 on 2024-10-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WizardStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True, verbose_name='Is this step required?')),
                ('step_type', models.CharField(choices=[('always', 'Always visible'), ('conditional', 'Visible based on conditions')], default='always', max_length=20, verbose_name='Step Type')),
                ('condition_name', models.CharField(blank=True, help_text='Choose the predefined condition to determine visibility of this step.', max_length=100, null=True, verbose_name='Condition Name')),
                ('handler_class', models.CharField(blank=True, help_text='Define the handler class to be used for this step.', max_length=100, null=True, verbose_name='Handler Class')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
