# Generated by Django 3.2.25 on 2024-10-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardstep',
            name='editable_in_backend',
            field=models.BooleanField(default=True, verbose_name='Is this step editable in the backend?'),
        ),
        migrations.AlterField(
            model_name='wizardstep',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
