# Generated by Django 3.2.21 on 2024-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_auto_20241003_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardstep',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
