# Generated by Django 3.2.25 on 2024-10-30 16:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_wizardstep_link_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardstep',
            name='display_in_navigation',
            field=models.BooleanField(default=True, verbose_name='Display in navigation'),
        ),
        migrations.AlterField(
            model_name='wizardstep',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
