# Generated by Django 3.2.25 on 2024-11-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0005_auto_20241030_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardstep',
            name='lead',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
