# Generated by Django 3.2.25 on 2024-11-28 14:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0006_wizardstep_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizardstep',
            name='condition_name',
        ),
        migrations.RemoveField(
            model_name='wizardstep',
            name='handler_class',
        ),
        migrations.RemoveField(
            model_name='wizardstep',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='wizardstep',
            name='step_type',
        ),
        migrations.AlterField(
            model_name='wizardstep',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Free form description, with images if necessary', null=True),
        ),
        migrations.AlterField(
            model_name='wizardstep',
            name='lead',
            field=models.CharField(blank=True, help_text='Big text displayed below the title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='wizardstep',
            name='slug',
            field=models.SlugField(blank=True, help_text='Part of the url. Must be unique, and not contain spaces, accentuated letters or special characters.', unique=True),
        ),
        migrations.AlterField(
            model_name='wizardstep',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Displayed next to the title, in smaller caps. Not visible in navigation.', max_length=50),
        ),
        migrations.AlterField(
            model_name='wizardstep',
            name='title',
            field=models.CharField(help_text='The title is used in navigation and on top of the page', max_length=50),
        ),
    ]
