# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-10 15:31
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Function code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Function name")),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Rate"),
                ),
                (
                    "rate_mode",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("daily", "Daily"), ("monthly", "Monthly")],
                        max_length=20,
                        verbose_name="Rate mode",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
