# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 16:25
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("start", models.DateField(verbose_name="Start date")),
                ("end", models.DateField(verbose_name="End date")),
                (
                    "set_as_exported",
                    models.BooleanField(default=True, verbose_name="Set as exported"),
                ),
                (
                    "include_already_exported",
                    models.BooleanField(
                        default=False, verbose_name="Include already exported sessions"
                    ),
                ),
                ("add_details", models.BooleanField(default=False, verbose_name="Add details")),
                ("csv_file", models.FileField(blank=True, null=True, upload_to="payroll")),
                (
                    "exported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Exported by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
