# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rate'),
        ),
    ]
