# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20220818_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='rate_mode',
            field=models.CharField(choices=[(b'day', 'Daily'), (b'hour', 'Hourly')], max_length=20, verbose_name='Rate mode'),
        ),
    ]
