# Generated by Django 3.2.16 on 2022-12-15 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0004_auto_20220818_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="exported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Exported by",
            ),
        ),
    ]
