"""Production settings and globals."""

from .production import *


TEMPLATES[0]["DIRS"] = [
    normpath(join(SITE_ROOT, "themes", "coppet", "templates")),
    normpath(join(SITE_ROOT, "templates")),
]

STATICFILES_DIRS = (
    normpath(join(SITE_ROOT, "themes", "coppet", "static")),
    normpath(join(SITE_ROOT, "static")),
)

KEPCHUP_USE_ABSENCES = False
KEPCHUP_IMPORT_CHILDREN = False
KEPCHUP_PREFILL_YEARS_WITH_TEACHERS = True

KEPCHUP_SEND_PRESENCE_LIST = True
KEPCHUP_SEND_COPY_CONTACT_MAIL_TO_ADMIN = True
KEPCHUP_NO_PAYMENT = False
KEPCHUP_DISPLAY_FREE_WHEN_PRICE_IS_0 = True
KEPCHUP_NO_TERMS = False
KEPCHUP_CHILD_SCHOOL = False
KEPCHUP_EMERGENCY_NUMBER_MANDATORY = True
KEPCHUP_DISPLAY_PARENT_CITY = False
KEPCHUP_DISPLAY_PARENT_EMAIL = True
KEPCHUP_DISPLAY_PARENT_PHONE = False
KEPCHUP_REGISTER_ACCOUNTS_AT_ANY_TIME = True
KEPCHUP_INSTRUCTORS_CAN_REMOVE_REGISTRATIONS = True
