# Generated by Django 3.2.25 on 2026-09-22 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_registration_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=255)),
                ('course_number', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('evaluation', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('instructors', models.CharField(max_length=500)),
                ('pdf', models.BinaryField(null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('mail_status', models.CharField(choices=[('pending', 'Non envoyé'), ('sending', 'Envoi en cours / à vérifier'), ('sent', 'Envoyé'), ('failed', 'Échec — à vérifier')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'course_number'),
            },
        ),
        migrations.CreateModel(
            name='DiplomaBatch',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=100)),
                ('issued_on', models.DateField()),
                ('source_schema', models.CharField(max_length=63)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('logo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'À préparer'), ('queued', 'En attente de génération'), ('generating', 'Génération en cours'), ('ready', 'PDF prêts'), ('failed', 'Génération en échec')], default='draft', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('print_pdf', models.BinaryField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DiplomaSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='diplomas.diplomabatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiplomaEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('action', models.CharField(choices=[('created', 'Préparation créée'), ('edited', 'Diplôme corrigé'), ('message', 'Texte du mail modifié'), ('supplement', 'Pièce jointe ajoutée'), ('generate', 'Génération demandée'), ('generation_started', 'Génération démarrée'), ('generated', 'PDF archivé'), ('generation_completed', 'Génération terminée'), ('generation_failed', 'Échec de génération'), ('queue_failed', 'Échec de mise en file'), ('publish', 'Publication sur les comptes'), ('send', 'Envoi demandé'), ('mail_started', 'Envoi démarré'), ('mail_sent', 'Mail accepté par le serveur'), ('mail_failed', 'Échec d’envoi'), ('mail_queue_failed', 'Échec de mise en file du mail'), ('printed', 'Impression confirmée'), ('print_downloaded', 'PDF d’impression téléchargé'), ('downloaded', 'Diplôme téléchargé')], max_length=40)),
                ('detail', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='diplomas.diplomabatch')),
                ('diploma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='diplomas.diploma')),
            ],
            options={
                'ordering': ('-created', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='diploma',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomas', to='diplomas.diplomabatch'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='diploma',
            constraint=models.UniqueConstraint(fields=('batch', 'source_registration_id'), name='diploma_batch_registration'),
        ),
    ]
