# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-02 14:07
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0011_child_avs'),
        ('activities', '0015_add_local_city_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Child')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Course')),
            ],
            options={
                'ordering': ('course', 'created'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='waitingslot',
            unique_together=set([('child', 'course')]),
        ),
    ]
