# Generated by Django 3.2.25 on 2024-10-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_alter_extraneed_step'),
        ('waiting_slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingslot',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_slots', to='activities.course'),
        ),
    ]
