# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-13 04:08
from __future__ import absolute_import, unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=30, verbose_name="Emergency number"
            ),
        ),
    ]
