# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 10:03
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20201013_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, verbose_name='Phone number'),
        ),
    ]
