# Generated by Django 3.2.20 on 2023-10-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0020_auto_20231009_1802'),
        ('appointments', '0006_appointment_type_part2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='registrations.child'),
        ),
    ]
