# Generated by Django 3.2.25 on 2024-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_auto_20241017_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='appointment_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return'), ('other', 'Other')], default='pickup', max_length=10),
        ),
    ]
